{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onyx.fullname" . }}-ingress-webserver
  annotations:
    {{- if not .Values.ingress.className }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
    cert-manager.io/cluster-issuer: {{ include "onyx.fullname" . }}-letsencrypt
    kubernetes.io/tls-acme: "true"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.webserver.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "onyx.fullname" . }}-webserver
                port:
                  number: {{ .Values.webserver.service.servicePort }}
  tls:
    - hosts:
        - {{ .Values.ingress.webserver.host }}
      secretName: {{ include "onyx.fullname" . }}-ingress-webserver-tls
{{- end }}