name: Release Devtools

on:
  push:
    tags:
      - "ods/v*.*.*"

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: release-devtools
    permissions:
      id-token: write
    timeout-minutes: 10
    strategy:
      matrix:
        os-arch:
          - { goos: "linux", goarch: "amd64" }
          - { goos: "linux", goarch: "arm64" }
          - { goos: "windows", goarch: "amd64" }
          - { goos: "windows", goarch: "arm64" }
          - { goos: "darwin", goarch: "amd64" }
          - { goos: "darwin", goarch: "arm64" }
          - { goos: "", goarch: "" }
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # ratchet:astral-sh/setup-uv@v7
        with:
          enable-cache: false
          version: "0.9.9"
      - run: |
          GOOS="${{ matrix.os-arch.goos }}" \
          GOARCH="${{ matrix.os-arch.goarch }}" \
          uv build --wheel
        working-directory: tools/ods
      - run: uv publish
        working-directory: tools/ods
